import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex items-center justify-between w-[100%] h-[60px] bg-blue-500 box-border px-[30px] py-[12px]">
          <div className="logo">
              RESUME-FIT-CHECKER
          </div>
          <nav>
            <ul className = "flex flex-row gap-[10px]">
              <li><Link href="/dashboard">Dashboard</Link></li>
              <li><Link href="/upload">Upload</Link></li>
              <li><Link href="#">Login</Link></li>
              <li><Link href="#">Logout</Link></li>
            </ul>
          </nav>
        </header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
